# Generated by Django 4.2.11 on 2024-04-15 20:23
import os

from django.conf import settings
from django.core.files import File
from django.db import migrations
from oscar.core.loading import get_model
from oscar.apps.address.models import Country


def populate_initial_data():
    """
    Initial migration to populate database with example data.

    This migration inserts example data into the database to facilitate deploying
    the application with pre-populated data as a proof of concept. The example data
    includes sample products, categories, and fulfillment partners to demonstrate
    the functionality of the application.

    This migration is intended for use in a coding portfolio and should be run
    after creating the initial database schema to populate it with sample data.
    """
    Partner = get_model('partner', 'Partner')
    Address = get_model('address', 'Address')

    StockRecord = get_model('partner', 'StockRecord')
    Category = get_model('catalogue', 'Category')
    Product = get_model('catalogue', 'Product')
    ProductClass = get_model('catalogue', 'ProductClass')

    default_partner = Partner.objects.create(name='Make-up Style')
    argentina = Country.objects.get(iso_3166_1_a2='AR')

    Address.objects.create(line1="Alvear 137bis, Rosario",
                           state="Santa Fe",
                           postcode="2000",
                           country=argentina,
                           partner=default_partner)

    class_makeup = ProductClass.objects.create(name='Make-up')
    class_skincare = ProductClass.objects.create(name='Skincare')
    class_haircare = ProductClass.objects.create(name='Haircare')
    class_tools = ProductClass.objects.create(name='Tools and accessories')
    class_fragrance = Category.objects.create(name='Fragrance')

    category_lipstick = Category.objects.create(name='Lipstick')
    category_moisturizer = Category.objects.create(name='Moisturizer')
    category_hair_oil = Category.objects.create(name='Hair oil')
    category_hair_straightener = Category.objects.create(name='Hair straightener')
    category_eau_de_parfume = Category.objects.create(name='Eau De Parfume')

    default_products = [
        {
            'title': 'L\'Oréal Paris Rouge Signature Lipstick 134 | Empowered 7ml',
            'product_class': class_makeup,
            'category': category_lipstick,
            'image_filename': 'lipstick.png'
        },
        {
            'title': 'Cerave Moisturising Cream',
            'product_class': class_skincare,
            'category': category_moisturizer,
            'image_filename': 'cerave.jpeg'
        },
        {
            'title': 'Elvive Óleo Extraordinario',
            'product_class': class_haircare,
            'category': category_hair_oil,
            'image_filename': 'oleo.jpeg'
        },
        {
            'title': 'Remington Shine Therapy 1 inch Hair Straightener Iron',
            'product_class': class_tools,
            'category': category_hair_straightener,
            'image_filename': 'iron.jpeg'
        },
        {
            'title': 'CHRISTIAN DIOR J\'Adore Women Eau De Parfume Spray, 1.7 Ounce',
            'product_class': class_fragrance,
            'category': category_eau_de_parfume,
            'image_filename': 'jadore.png'
        },
    ]

    for product_data in default_products:
        image_path = os.path.join(settings.BASE_DIR, 'initial_data', 'migrations', 'images', product_data['image_filename'])
        with open(image_path, 'rb') as image_file:
            product = Product(
                name=product_data['name'],
                product_class=product_data['description'],
                category=product_data['category'],
                images=[File(image_file)],
            )
            product.save()
            StockRecord.objects.create(product=product, partner=default_partner)

    # default_lipstick = Product.objects.create(title='L\'Oréal Paris Rouge Signature Lipstick 134 | Empowered 7ml',
    #                                           product_class=class_makeup,
    #                                           category=category_lipstick,
    #                                           images=[])
    # default_skin_cream = Product.objects.create(title='Cerave Moisturising Cream',
    #                                             product_class=class_skincare,
    #                                             category=category_moisturizer,
    #                                             images=[])
    # default_hair_oil = Product.objects.create(title='Elvive Óleo Extraordinario',
    #                                           product_class=class_haircare,
    #                                           category=category_hair_oil,
    #                                           images=[])
    # default_iron = Product.objects.create(title='Remington Shine Therapy 1 inch Hair Straightener Iron',
    #                                       product_class=class_tools,
    #                                       category=category_hair_straightener,
    #                                       images=[])
    # default_perfume = Product.objects.create(title='CHRISTIAN DIOR J\'Adore Women Eau De Parfume Spray, 1.7 Ounce',
    #                                          product_class=class_fragrance,
    #                                          category=category_eau_de_parfume,
    #                                          images=[])

    # StockRecord.objects.create(product=default_lipstick, partner=default_partner)
    # StockRecord.objects.create(product=default_skin_cream, partner=default_partner)
    # StockRecord.objects.create(product=default_hair_oil, partner=default_partner)
    # StockRecord.objects.create(product=default_iron, partner=default_partner)
    # StockRecord.objects.create(product=default_perfume, partner=default_partner)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]
